codersalman/Hacktoberfest-2022

- Javascript/Registration_Form/Registration-template-master/Registration-template-master/README.md
- Javascript/Registration_Form/Registration-template-master/Registration-template-master/app.js
- Javascript/Registration_Form/Registration-template-master/Registration-template-master/index.html
- Javascript/Registration_Form/Registration-template-master/Registration-template-master/style.css
Hi, I have made a registration form using javascript and firebase.
The registered information will be displayed on the same page. 
Hope you would like and merge it.😊
waiting for the positive feedback.
> Registration_form

- Javascript/Random Number Generator/README.md
- Javascript/Random Number Generator/index.css
- Javascript/Random Number Generator/index.html
- Javascript/Random Number Generator/index.js
Issue solved : #10 
- HTML
- CSS
- Js
@codersalman ,Please merge it under `hacktoberfest`
> Added JavaScript Project

- Arduino/2led_1switch.ino
Controlling 2 LEDs with a single switch
> 2 LEDs, 1 Switch

- Arduino/arduino_traffic_light.ino
Arduino and LEDs are used to simulate a traffic light. This project is very simple to make and is really cool to watch.
> Arduino Traffic Light Simulator

- Javascript/Resources.md
> Added JavaScript resources

- Arduino/Line_follower_Bot.ino
- Arduino/Wifi_Controlled_Bot.ino
Now I have added the code for **Line Follower Bot** and this code can be uploaded in _NodeMcu 12E_ module Microcontroller.
> Line Follower Bot & Wifi Controlled Bot

- PHP/registration-page.php
Php with mysql registration page added
> Created registration-page.php

- React/color generator/README.md
- React/color generator/public/index.html
- React/color generator/src/App.js
- React/color generator/src/SingleColor.js
- React/color generator/src/color generator.css
- React/color generator/src/index.js
> color generator using ReactJS

- dev-tools.md
Adding dev tools in dev-tolls.md
#48
> adding new dev tolls

- Javascript/Calculator/index.css
- Javascript/Calculator/string.js
I noticed when the equal sign button is clicked, it displayed undefined. I've added a condition to check if string is empty, and also styled the buttons to have the border show when hovered over. Please review.
@Tanya1227 feel free to check out my changes as well.
> Refactored event listener

- PHP/login.php
> added the login function

- Javascript/Convert your PDF to Thumbnail - with PDFJS/Convert your PDF to Thumbnail img.html
Select pdf file, you will get a image of first page of PDF.
> Convert your PDF to Thumbnail img

- Javascript/Bmi Calculator/BMI.html
- Javascript/Bmi Calculator/BMI.js
- Javascript/Bmi Calculator/Readme.md
This program helps to know weather you are healthy or not using BMI calculator. It is a measurement term to know weather a person has a sound health or not.
> A program to Find body mass index

- Javascript/Rock_Paper_&_Scissor_Game/index.html
- Javascript/Rock_Paper_&_Scissor_Game/index.js
- Javascript/Rock_Paper_&_Scissor_Game/style.css
please add this pr as hacktoberfest 2022
> rock paper and scissor game add in javascript project

- Javascript/Calcula-Imc/index.js
- Javascript/Calcula-Imc/script.js
- Javascript/Calcula-Imc/style.css
site que calcula o índice de massa corporal de (imc) de acordo com seu peso e altura.
> calculadora de imc

- Javascript/fetch links from text files.html
my first hacktoberfest merge request
> fetch links from text files

- Digital clock/Design.css
- Digital clock/Main.html
Hi! I added a code of Digital Clock using Html, CSS, and JavaScript.
> Digital Clock with JavaScript Code Added

- Javascript/Movies App/index.html
- Javascript/Movies App/script.js
- Javascript/Movies App/style.css
Please review and merge my PR request for Hacktoberfest
> Added a movies App

- Javascript/Palindrome Birthday/README.md
- Javascript/Palindrome Birthday/index.html
- Javascript/Palindrome Birthday/script.js
- Javascript/Palindrome Birthday/style.css
Hey 
i added palindrome birthday app please merge
> #64-Palindrome birthday added

- React/react_search.js
Simple search function in react using data from typicode
> React Search

- React/Accordion/README.md
- React/Accordion/public/index.html
- React/Accordion/src/App.js
- React/Accordion/src/Question.js
- React/Accordion/src/accordion.css
- React/Accordion/src/data.js
- React/Accordion/src/index.js
- React/DisplayData/README.md
Please review my another ReactJS project and merge it with the main
> Accordion using ReactJS 🪗 

- Python/dino_automate_gui.py
Automate the Chrome Dino game using Python GUI Automation
> Automate Google Chrome dinosaur game

- Appscript/extract_all_email_address.gs
easily extract all the email addresses in your Gmail inbox and save it in Google Sheets.
> collect list of email address

- Appscript/chk_sheet_present.gs
check if a sheet present in google spreadsheet with a specific Name, if sheet not present then create a new once with same name it.
> CREATE NEW GOOGLE SPREADSHEET IF SHEET NOT EXIST

- React/reactjs_post_form_data
Post form data in Reactjs using FETCH API
> Reactjs Post Form Data

- Javascript/saveWebpageAsPDF.html
Download a page or part of page as pdf
> Save html page as pdf file

- Python/text_pre_processing.py
simple but effective code to pre process text removing stop words etc.
> Pre processing text before apply NLP

- Javascript/autocounter.js
Kindly review this contribution to hacktoberfest2022
> Created a javaScript auto counter program

- HTML - CSS/responsive-table.html
table layout change on mobile devices
> responsive table in html css
